# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

credentials:
  password: password
  user: user

images:
  grafana: grafana/grafana:4.1.1
  grafana_watcher: quay.io/coreos/grafana-watcher:v0.0.4
  pull_policy: IfNotPresent

network:
  node_port:
    enabled: true
    port: 30902
  port:
    name: web
    port: 3000

replicas:
  grafana: 2

resources:
  enabled: false
  grafana:
    limits:
      cpu: "200m"
      memory: "200Mi"
    requests:
      cpu: "100m"
      memory: "100Mi"
  grafana_watcher:
    limits:
      cpu: "100m"
      memory: "32Mi"
    requests:
      cpu: "50m"
      memory: "16Mi"

upgrades:
  pod_replacement_strategy: RollingUpdate
  revision_history: 3
  rolling_update:
    max_surge: 3
    max_unavailable: 1
