
# Kibana is served by a back end server. This setting specifies the port to use.
server.port: {{ .Values.config.server.port | default 5601 }}

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: {{ .Values.config.server.host | default "localhost" }}

# Enables you to specify a path to mount Kibana at if you are running behind a proxy. This only affects
# the URLs generated by Kibana, your proxy is expected to remove the basePath value before forwarding requests
# to Kibana. This setting cannot end in a slash.
#server.basePath: {{ .Values.config.server.base_path | quote }}

# The maximum payload size in bytes for incoming server requests.
#server.maxPayloadBytes: {{ .Values.config.server.max_payload_bytes | default 1048576 }}

# The Kibana server's name.  This is used for display purposes.
#server.name: {{ .Values.config.server.name | quote | default "" }}

# The URL of the Elasticsearch instance to use for all your queries.
elasticsearch.url: {{ .Values.config.elasticsearch.url | quote | default "http://localhost:9200"}}

# When this setting's value is true Kibana uses the hostname specified in the server.host
# setting. When the value of this setting is false, Kibana uses the hostname of the host
# that connects to this Kibana instance.
elasticsearch.preserveHost: {{ .Values.config.elasticsearch.preserve_host | default true }}

# Kibana uses an index in Elasticsearch to store saved searches, visualizations and
# dashboards. Kibana creates a new index if the index doesn't already exist.
kibana.index: {{ .Values.config.kibana.index | default ".kibana" }}

# The default application to load.
kibana.defaultAppId: {{ .Values.config.kibana.default_app_id | default "discover" }}

# If your Elasticsearch is protected with basic authentication, these settings provide
# the username and password that the Kibana server uses to perform maintenance on the Kibana
# index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
# is proxied through the Kibana server.
#elasticsearch.username: {{ .Values.config.elasticsearch.username | quote | default "" }}
#elasticsearch.password: {{ .Values.config.elasticsearch.password | quote | default "" }}

# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
# server.ssl.enabled: {{ .Values.config.server.ssl.enabled | default false }}
# server.ssl.certificate: {{ .Values.config.server.ssl.certificate | default "" }}
# server.ssl.key: {{ .Values.config.server.ssl.key | default "" }}

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files validate that your Elasticsearch backend uses the same key files.
# elasticsearch.ssl.certificate: {{ .Values.config.elasticsearch.ssl.certificate | default "" }}
# elasticsearch.ssl.key: {{ .Values.config.elasticsearch.ssl.key | default "" }}

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
# example: elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]
# elasticsearch.ssl.certificateAuthorities: {{ .Values.config.elasticsearch.ssl.certificate_authorities | default "[]" }}

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
# elasticsearch.ssl.verificationMode: {{ .Values.config.elasticsearch.ssl.verification_mode | default "full" }}

# Time in milliseconds to wait for Elasticsearch to respond to pings. Defaults to the value of
# the elasticsearch.requestTimeout setting.
elasticsearch.pingTimeout: {{ .Values.config.elasticsearch.ping_timeout | default 1500 }}

# Time in milliseconds to wait for responses from the back end or Elasticsearch. This value
# must be a positive integer.
elasticsearch.requestTimeout: {{ .Values.config.elasticsearch.request_timeout | default 30000 }}

# List of Kibana client-side headers to send to Elasticsearch. To send *no* client-side
# headers, set this value to [] (an empty list).
# example: elasticsearch.requestHeadersWhitelist: [ authorization ]
#elasticsearch.requestHeadersWhitelist: {{ .Values.config.elasticsearch.request_headers_whitelist | default "[]" }}

# Header names and values that are sent to Elasticsearch. Any custom headers cannot be overwritten
# by client-side headers, regardless of the elasticsearch.requestHeadersWhitelist configuration.
#elasticsearch.customHeaders: {{ .Values.config.elasticsearch.custom_headers | default "{}" }}

# Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
elasticsearch.shardTimeout: {{ .Values.config.elasticsearch.shard_timeout | default 0 }}

# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying.
elasticsearch.startupTimeout: {{ .Values.config.elasticsearch.startup_timeout | default 5000 }}

# Specifies the path where Kibana creates the process ID file.
#pid.file: {{ .Values.config.pid.file | default "none" }}

# Enables you specify a file where Kibana stores log output.
logging.dest: {{ .Values.config.logging.destination | quote | default "stdout" }}

# Set the value of this setting to true to suppress all logging output.
logging.silent: {{ .Values.config.logging.silent | default false }}

# Set the value of this setting to true to suppress all logging output other than error messages.
logging.quiet: {{ .Values.config.logging.quiet | default false }}

# Set the value of this setting to true to log all events, including system usage information
# and all requests.
logging.verbose: {{ .Values.config.logging.verbose | default false }}

# Set the interval in milliseconds to sample system and process performance
# metrics. Minimum is 100ms. Defaults to 5000.
# ops.interval: {{ .Values.config.ops.interval | default 5000 }}

# The default locale. This locale can be used in certain circumstances to substitute any missing
# translations.
#i18n.defaultLocale: {{ .Values.config.il8n.default_locale | quote | default "en" }}
